export enum WlasciwoscEtykiety {

  GLEBA = 'Gleba',
  GRUPA = 'Grupa',
  KWIAT = 'Kwiat',
  OWOC = 'Owoc',
  ODCZYN = 'Odczyn',
  PODGRUPA = 'Podgrupa',
  POKROJ = 'Pokrój',
  STANOWISKO = 'Stanowisko',
  WALOR = 'Walor',
  WILGOTNOSC = 'Wilgotność',
  ZASTOSOWANIE = 'Zastosowanie',
  KOLOR_LISCI = 'Kolor liści',
  KOLOR_KWIATOW = 'Kolor kwiatów',
  FORMA = 'Forma',
  SILA_WZROSTU = 'Siła wzrostu',
  ZIMOZIELONOSC = 'Zimozieloność',
  OKRES_KWITNIENIA = 'Okres kwitnienia',
  OKRES_OWOCOWANIA = 'Okres owocowania',
}
